### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by wiiznokes** [wiiznokes/gitnote#45]
```
06-13 19:58:31.369  5012  5012 E AndroidRuntime: FATAL EXCEPTION: main
06-13 19:58:31.369  5012  5012 E AndroidRuntime: Process: io.github.wiiznokes.gitnote, PID: 5012
06-13 19:58:31.369  5012  5012 E AndroidRuntime: java.lang.IllegalStateException: CompositionLocal LocalLifecycleOwner not present
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at h1.d.c(Unknown Source:8)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at R1.l.getValue(Unknown Source:20)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at I.q.L(Unknown Source:32)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at I.o.m(Unknown Source:4)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at F1.x.d(Unknown Source:40)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at A1.i.k(Unknown Source:82)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at Q.a.k(Unknown Source:51)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at p0.e0.a(Unknown Source:22)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at A1.h.k(Unknown Source:217)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at Q.a.k(Unknown Source:51)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at B2.f.s(Unknown Source:4)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at I.q.b(Unknown Source:145)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at p0.f0.a(Unknown Source:282)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at G.Z0.k(Unknown Source:368)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at Q.a.k(Unknown Source:51)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at B2.f.s(Unknown Source:4)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at I.q.b(Unknown Source:145)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at p0.Q.a(Unknown Source:482)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at p0.X0.k(Unknown Source:184)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at Q.a.k(Unknown Source:51)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at B2.f.s(Unknown Source:4)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at I.q.a(Unknown Source:217)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at p0.X0.k(Unknown Source:146)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at Q.a.k(Unknown Source:51)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at I.q.F(Unknown Source:14)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at I.o.r(Unknown Source:121)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at I.o.k(Unknown Source:10)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at I.v.k(Unknown Source:35)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at I.u0.a(Unknown Source:43)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at I.v.l(Unknown Source:8)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at I.v.e(Unknown Source:2)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at o.h1.l(Unknown Source:669)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at p0.u.setOnViewTreeOwnersAvailable(Unknown Source:6)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at p0.Y0.e(Unknown Source:8)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at p0.Y0.c(Unknown Source:18)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at androidx.lifecycle.u.a(Unknown Source:22)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at androidx.lifecycle.v.a(Unknown Source:215)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at o.h1.l(Unknown Source:639)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at p0.u.onAttachedToWindow(Unknown Source:97)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.View.dispatchAttachedToWindow(View.java:22257)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3494)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3501)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3501)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3501)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3501)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3207)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2659)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9789)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1399)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:938)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:959)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:232)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:317)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8501)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
06-13 19:58:31.369  5012  5012 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
06-13 19:58:31.370  1312  5039 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
06-13 19:58:31.370  1312  2666 W ActivityTaskManager:   Force finishing activity io.github.wiiznokes.gitnote/.MainActivity
06-13 19:58:31.371  2386  2412 V WindowManagerShell: Transition requested (#893): android.os.BinderProxy@533681a TransitionRequestInfo { type = CLOSE, triggerTask = null, pipTask = null, remoteTransition = null, displayChange = null, flags = 16, debugId = 893 }
06-13 19:58:31.375  1312  1663 I ActivityManager: Showing crash dialog for package io.github.wiiznokes.gitnote u0

```

**Comment by wiiznokes** [comment]
https://stackoverflow.com/questions/78490378/java-lang-illegalstateexception-compositionlocal-locallifecycleowner-not-presen
